name: Java CI with Gradle

on:
  push:
    tags:
      - 'v**'
    branches: [ $default-branch, 'feature/#**' ]
  pull_request:
    branches: [ $default-branch, 'feature/#**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Use Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build docker container with gradle
        run: gradle wrapper && ./gradlew jib -Djib.to.image=$IMAGE:$TAG -Djib.to.auth.username=$USER -Djib.to.auth.password=$PASSWORD
