name: Service pipeline

on:
  push:
    tags:
      - 'v**'
    branches: [ $default-branch, 'feature/#**' ]
  pull_request:
    branches: [ $default-branch, 'feature/#**' ]

env:
  IMAGE: nkrivenko/eosio-proxy-service

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set feature environment variables
        run: |
          echo "TAG=$(git symbolic-ref --short HEAD | sed -E 's/[\/#]/-/g')" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/heads/feature')
      - name: Set latest environment variables
        run: |
          echo "TAG=latest" >> $GITHUB_ENV
        if: contains( github.ref, 'master' )
      - name: Set tag environment variables
        run: |
          echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/tags')
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Use Gradle
        uses: gradle/gradle-build-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build docker container with gradle
        run: gradle wrapper && ./gradlew jib -Djib.to.image=${{ env.IMAGE }}:${{ env.TAG }}
  test:
    runs-on: ubuntu-20.04
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Use Gradle
        uses: gradle/gradle-build-action@v2
      - name: Launch unit tests
        run: gradle wrapper && ./gradlew test
      - name: jacoco-badge-generator
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2.6.1
        with:
          jacoco-csv-file: build/reports/jacoco/test/jacocoTestReport.csv
      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"

      - name: Commit the badge (if it changed)
        run: |
          if [[ `git status --porcelain` ]]; then
                  git config --global user.name 'UserName'
                  git config --global user.email 'useremail@gmail.com'
                  git add -A
                  git commit -m "[CI] Autogenerated JaCoCo coverage badge"
                  git push
          fi

      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: reports/jacoco/test
